# Make sure to change the action name here (must be unique).
# Update the rest as needed.
name: 'unique-action-goes-here'
description: 'BRIEF DESCRIPTION OF YOUR ACTION'
branding: # Look at documentation for branding options/requirements. These are my favorites.
  icon: 'book-open'
  color: 'green'
inputs:
  input-one:  
    description: 'Description of input-one'
    required: false
    default: 'default value goes here'
  input-two:
    description: 'Description of input-two'
    required: false
    default: 'default value goes here'
outputs:
  exit-code:
    description: '0 if successful or non-zero if unsuccessful'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.input-one }}
    - ${{ inputs.input-two }}
